import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./navBar";
import AuthProvider from "./auth/Provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});



export const metadata: Metadata = {
  title: "NEXT JS LRN",
  description: "Generated by Mustafa Alani",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={roboto.className + " " + geistSans.className + " " + geistMono.className}
      >
        <AuthProvider>
            <NavBar/>
            <main className="p-5 bg-base-200 min-h-screen flex flex-col gap-5">
              {children}
            </main>
        </AuthProvider>
      </body>
    </html>
  );
}
